export const defaultTheme = {
  container: 'colorpickr round inline-block bg-gray-faint w240 round px12 py12 txt-xs',
  topWrapper: 'flex-parent relative',
  bottomWrapper: 'flex-parent mt6',
  gradientContainer: 'flex-child flex-child--no-shrink pb12 h120 w120 z1',
  controlsContainer: 'flex-child flex-child--grow ml12',
  toggleGroup: 'toggle-group w-full mb12',
  toggleContainer: 'toggle-container w-full',
  toggle: 'toggle py0 px6 toggle--gray',
  inputModeContainer: 'mb3 flex-parent',
  alphaContainer: 'mb3',
  tileBackground: 'bg-tile bg-white',
  active: 'is-active',
  slider: 'slider',
  colorModeSlider: 'colormode-slider',
  colorModeSliderR: 'colormode-slider-r',
  colorModeSliderG: 'colormode-slider-g',
  colorModeSliderB: 'colormode-slider-b',
  colorModeSliderH: 'colormode-slider-h',
  gradient: 'absolute top right bottom left',
  gradientHue: 'gradient-hue',
  gradientSaturation: 'gradient-saturation',
  gradientLight: 'gradient-light',
  gradientRHigh: 'gradient-rgb gradient-r-high',
  gradientRLow: 'gradient-rgb gradient-r-low',
  gradientGHigh: 'gradient-rgb gradient-g-high',
  gradientGLow: 'gradient-rgb gradient-g-low',
  gradientBHigh: 'gradient-rgb gradient-b-high',
  gradientBLow: 'gradient-rgb gradient-b-low',
  xyControlContainer: 'relative w-full h-full cursor-pointer',
  xyControl: 'xy-control absolute z1 unselectable cursor-move',
  xyControlDark: 'xy-control-dark',
  numberInputContainer: 'flex-child flex-child--grow relative',
  numberInputLabel: 'absolute top left bottom pl6 flex-parent flex-parent--center-cross color-gray-light txt-bold',
  numberInput: 'w-full pl18 pr3 input input--s txt-mono txt-xs bg-white',
  modeInputContainer: 'flex-child flex-child--no-shrink flex-parent flex-parent--center-cross w24',
  modeInput: 'cursor-pointer',
  swatch: 'w-full h-full',
  swatchCompareContainer: 'flex-child flex-child--no-shrink grid w120 round scroll-hidden',
  currentSwatchContainer: 'col h24 border-r border--gray-faint',
  currentSwatch: 'txt-bold align-center color-transparent color-white-on-hover transition',
  newSwatchContainer: 'col h24',
  hexContainer: 'flex-child flex-child--grow ml12 relative'
};
