export const defaultTheme = {
  container: 'colorpickr round inline-block w240 txt-xs flex flex--column',
  bottomWrapper: 'flex flex--column',
  gradientContainer: 'flex-child-no-shrink mb6 h240 w-full z1',
  sliderContainer: 'flex-child-no-shrink mb6',
  controlsContainer: 'flex-child-no-shrink border-b border--gray-light',
  modeToggle: 'link link--gray pb6 px3 mb-neg1',
  modeToggleActive: 'is-active border-b border-gray',
  inputModeContainer: 'mb3 flex flex--center-cross',
  alphaContainer: 'mb3',
  tileBackground: 'bg-tile',
  active: 'is-active',
  slider: 'slider',
  colorSpaceSelect: 'txt-s color-gray',
  gradient: 'absolute top right bottom left',
  gradientHue: 'gradient-hue',
  xyControlContainer: 'relative w-full h-full cursor-pointer',
  xyControl:
    'absolute z1 round-full border border--2 border--white w18 h18 cursor-move',
  xyControlDark: 'border--black',
  numberInputContainer: 'flex-child-grow relative',
  numberInputLabel:
    'absolute top left bottom pl6 flex flex--center-cross color-gray-light txt-bold',
  numberInput: 'w-full pl18 pr3 input input--s txt-mono',
  modeInput: 'cursor-pointer',
  swatch: 'w-full h-full',
  modeInputContainer: 'flex mb12',
  colorSpaceContainer: 'w-1/2 h24 flex flex--center-cross',
  colorInputContainer: 'w-1/2',
  swatchCompareContainer: 'flex round overflow-hidden',
  currentSwatchContainer: 'w-1/2 h24 border-r border--gray-faint',
  currentSwatch:
    'txt-bold align-center color-transparent color-white-on-hover transition',
  newSwatchContainer: 'w-1/2 h24',
  hexContainer: 'flex-child-grow ml12 relative'
};
