export const defaultTheme = {
  container:
    'colorpickr round inline-block bg-gray-faint w240 round px12 py12 txt-xs',
  topWrapper: 'flex relative',
  bottomWrapper: 'flex mt6',
  gradientContainer: 'flex-child-no-shrink pb12 h120 w120 z1',
  controlsContainer: 'flex-child-grow ml12',
  toggleGroup: 'toggle-group wmax-full mb12',
  toggleContainer: 'toggle-container w-full',
  toggle: 'toggle toggle--s toggle--gray',
  inputModeContainer: 'mb3 flex',
  alphaContainer: 'mb3',
  tileBackground: 'bg-tile bg-white',
  active: 'is-active',
  slider: 'slider',
  colorModeSlider: 'colormode-slider',
  colorModeSliderR: 'colormode-slider-r',
  colorModeSliderG: 'colormode-slider-g',
  colorModeSliderB: 'colormode-slider-b',
  colorModeSliderH: 'colormode-slider-h',
  gradient: 'absolute top right bottom left',
  gradientHue: 'gradient-hue',
  gradientSaturation: 'gradient-saturation',
  gradientLight: 'gradient-light',
  gradientRHigh: 'gradient-rgb gradient-r-high',
  gradientRLow: 'gradient-rgb gradient-r-low',
  gradientGHigh: 'gradient-rgb gradient-g-high',
  gradientGLow: 'gradient-rgb gradient-g-low',
  gradientBHigh: 'gradient-rgb gradient-b-high',
  gradientBLow: 'gradient-rgb gradient-b-low',
  xyControlContainer: 'relative w-full h-full cursor-pointer',
  xyControl: 'xy-control absolute z1 unselectable cursor-move',
  xyControlDark: 'xy-control-dark',
  numberInputContainer: 'flex-child-grow relative',
  numberInputLabel:
    'absolute top left bottom pl6 flex flex--center-cross color-gray-light txt-bold',
  numberInput: 'w-full pl18 pr3 input input--s txt-mono',
  modeInputContainer: 'flex-child-no-shrink flex flex--center-cross w24',
  modeInput: 'cursor-pointer',
  swatch: 'w-full h-full',
  swatchCompareContainer:
    'flex-child-no-shrink grid w120 round overflow-hidden',
  currentSwatchContainer: 'col col--auto h24 border-r border--gray-faint',
  currentSwatch:
    'txt-bold align-center color-transparent color-white-on-hover transition',
  newSwatchContainer: 'col col--auto h24',
  hexContainer: 'flex-child-grow ml12 relative'
};
